project:
  type: website
  output-dir: docs

website:
  title: "Ramya Thiyagarajan"
  description: "Welcome to My Website!"
  image: img/myimage.jpg
  favicon: img/fav.png

navbar:
  pinned: true
  logo: /img/Logo.png
  left:
    - text: "Projects"
      href: projects/index.qmd
    - text: "CV"
      href: cv/index.qmd
    - text: "Osteoporosis dashboard"
      href: dashboard/index.qmd
  right:
    - icon: linkedin
      href: https://www.linkedin.com/in/ramya-thiyagarajan-9a6205230
    - icon: envelope
      href: "mailto:ramya.thiyagarajan@gmail.com"

execute:
  freeze: true

format:
  html:
    fontsize: 1.1em
    theme: pulse
    toc: false
    anchor-sections: true
    fig-cap-location: margin
    footnotes-hover: true
